# Generated by Django 4.2 on 2023-09-05 04:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Customer", new_name="InforAccount",),
    ]
