# Generated by Django 4.2 on 2023-09-09 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_alter_category_options_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0002_rename_customer_inforaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inforaccount",
            name="city",
            field=models.CharField(
                choices=[("My", "VietNam"), ("aaa", "DDD")], max_length=50
            ),
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="item.item"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
